### PR TITLE
simplify hash merge

### PR DESCRIPTION
**Pull request by timoschilling**

### CODE REVIEW

**Review by varyonic — APPROVED** [review]
;-)

**Review by cfurrow — APPROVED** [review]
Looks good to me! Thanks!

**Comment by cfurrow** [comment]
I'll get this merged in, and bump the version

**Comment by cfurrow** [comment]
Wow, I had no idea this had been sitting so long!

**Comment by varyonic** [comment]
No worries.  Just poking around, happy to see Lumosity publishing ActiveAdmin gems, amused to see Timo was here before me.

**Comment by seunghyo** [comment]
hi @cfurrow

**Comment by cfurrow** [comment]
hah, hello @seunghyo!

**Comment by azach** [comment]
that's cool I didn't want a hello @cfurrow

**Comment by cfurrow** [comment]
then you won't get one, @azach

**Pull request merged**
